import os

def write(path, content):
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f'[OK] {path}')

def replace(path, old, new):
    with open(path, 'r', encoding='utf-8') as f:
        content = f.read()
    if old not in content:
        print(f'[ERRO] Trecho nao encontrado em {path}')
        return
    with open(path, 'w', encoding='utf-8') as f:
        f.write(content.replace(old, new, 1))
    print(f'[OK] {path}')

# ── 1. review_form_page.dart ──────────────────────────────────────────────────

write(
    os.path.join('lib', 'features', 'reviews', 'review_form_page.dart'),
    "import 'package:flutter/material.dart';\n"
    "import '../../data/models/review_model.dart';\n"
    "import '../../data/models/user_model.dart';\n"
    "import '../../data/repositories/reviews_repository.dart';\n"
    "\n"
    "class ReviewFormPage extends StatefulWidget {\n"
    "  final String providerId;\n"
    "  final String providerName;\n"
    "  final UserModel currentUser;\n"
    "\n"
    "  const ReviewFormPage({\n"
    "    super.key,\n"
    "    required this.providerId,\n"
    "    required this.providerName,\n"
    "    required this.currentUser,\n"
    "  });\n"
    "\n"
    "  @override\n"
    "  State<ReviewFormPage> createState() => _ReviewFormPageState();\n"
    "}\n"
    "\n"
    "class _ReviewFormPageState extends State<ReviewFormPage> {\n"
    "  final _commentController = TextEditingController();\n"
    "  final _reviewsRepository = ReviewsRepository();\n"
    "  int _rating = 5;\n"
    "  bool _isLoading = false;\n"
    "  String? _errorMessage;\n"
    "\n"
    "  @override\n"
    "  void dispose() {\n"
    "    _commentController.dispose();\n"
    "    super.dispose();\n"
    "  }\n"
    "\n"
    "  Future<void> _submit() async {\n"
    "    setState(() {\n"
    "      _isLoading = true;\n"
    "      _errorMessage = null;\n"
    "    });\n"
    "    try {\n"
    "      final review = ReviewModel(\n"
    "        id: '',\n"
    "        providerId: widget.providerId,\n"
    "        reviewerUid: widget.currentUser.uid,\n"
    "        reviewerName: widget.currentUser.displayName,\n"
    "        rating: _rating,\n"
    "        comment: _commentController.text.trim(),\n"
    "        createdAt: DateTime.now(),\n"
    "      );\n"
    "      await _reviewsRepository.addReview(review: review);\n"
    "      if (mounted) {\n"
    "        ScaffoldMessenger.of(context).showSnackBar(\n"
    "          const SnackBar(content: Text('Avaliacao enviada. Obrigado!')),\n"
    "        );\n"
    "        Navigator.pop(context);\n"
    "      }\n"
    "    } catch (e) {\n"
    "      if (mounted) {\n"
    "        setState(() => _errorMessage = 'Erro ao enviar. Tente novamente.');\n"
    "      }\n"
    "    } finally {\n"
    "      if (mounted) setState(() => _isLoading = false);\n"
    "    }\n"
    "  }\n"
    "\n"
    "  String _ratingLabel(int rating) {\n"
    "    if (rating <= 2) return 'Pessimo';\n"
    "    if (rating <= 4) return 'Ruim';\n"
    "    if (rating <= 6) return 'Regular';\n"
    "    if (rating <= 8) return 'Bom';\n"
    "    if (rating == 9) return 'Muito bom';\n"
    "    return 'Excelente';\n"
    "  }\n"
    "\n"
    "  Color _ratingColor(int rating) {\n"
    "    if (rating <= 4) return Colors.red;\n"
    "    if (rating <= 6) return Colors.orange;\n"
    "    if (rating <= 8) return Colors.amber.shade700;\n"
    "    return Colors.green;\n"
    "  }\n"
    "\n"
    "  @override\n"
    "  Widget build(BuildContext context) {\n"
    "    return Scaffold(\n"
    "      appBar: AppBar(title: const Text('Avaliar prestador')),\n"
    "      body: SingleChildScrollView(\n"
    "        padding: const EdgeInsets.all(20),\n"
    "        child: Column(\n"
    "          crossAxisAlignment: CrossAxisAlignment.stretch,\n"
    "          children: [\n"
    "            Text(\n"
    "              widget.providerName,\n"
    "              style: const TextStyle(\n"
    "                fontSize: 20,\n"
    "                fontWeight: FontWeight.bold,\n"
    "              ),\n"
    "            ),\n"
    "            const SizedBox(height: 28),\n"
    "            const Text(\n"
    "              'Sua nota',\n"
    "              style: TextStyle(fontSize: 16, fontWeight: FontWeight.w600),\n"
    "            ),\n"
    "            const SizedBox(height: 16),\n"
    "            Row(\n"
    "              mainAxisAlignment: MainAxisAlignment.center,\n"
    "              children: [\n"
    "                IconButton(\n"
    "                  onPressed: _rating > 1\n"
    "                      ? () => setState(() => _rating--)\n"
    "                      : null,\n"
    "                  icon: const Icon(Icons.remove_circle_outline, size: 36),\n"
    "                  color: Theme.of(context).colorScheme.primary,\n"
    "                ),\n"
    "                const SizedBox(width: 12),\n"
    "                Container(\n"
    "                  width: 72,\n"
    "                  height: 72,\n"
    "                  alignment: Alignment.center,\n"
    "                  decoration: BoxDecoration(\n"
    "                    color: _ratingColor(_rating),\n"
    "                    shape: BoxShape.circle,\n"
    "                  ),\n"
    "                  child: Text(\n"
    "                    '$_rating',\n"
    "                    style: const TextStyle(\n"
    "                      fontSize: 32,\n"
    "                      fontWeight: FontWeight.bold,\n"
    "                      color: Colors.white,\n"
    "                    ),\n"
    "                  ),\n"
    "                ),\n"
    "                const SizedBox(width: 12),\n"
    "                IconButton(\n"
    "                  onPressed: _rating < 10\n"
    "                      ? () => setState(() => _rating++)\n"
    "                      : null,\n"
    "                  icon: const Icon(Icons.add_circle_outline, size: 36),\n"
    "                  color: Theme.of(context).colorScheme.primary,\n"
    "                ),\n"
    "              ],\n"
    "            ),\n"
    "            const SizedBox(height: 8),\n"
    "            Center(\n"
    "              child: Text(\n"
    "                _ratingLabel(_rating),\n"
    "                style: TextStyle(\n"
    "                  fontSize: 16,\n"
    "                  fontWeight: FontWeight.w500,\n"
    "                  color: _ratingColor(_rating),\n"
    "                ),\n"
    "              ),\n"
    "            ),\n"
    "            const SizedBox(height: 4),\n"
    "            const Center(\n"
    "              child: Text(\n"
    "                'escala de 1 a 10',\n"
    "                style: TextStyle(fontSize: 12, color: Colors.grey),\n"
    "              ),\n"
    "            ),\n"
    "            const SizedBox(height: 24),\n"
    "            TextField(\n"
    "              controller: _commentController,\n"
    "              decoration: const InputDecoration(\n"
    "                labelText: 'Comentario (opcional)',\n"
    "                border: OutlineInputBorder(),\n"
    "                alignLabelWithHint: true,\n"
    "              ),\n"
    "              maxLines: 4,\n"
    "              textCapitalization: TextCapitalization.sentences,\n"
    "            ),\n"
    "            if (_errorMessage != null) ...[\n"
    "              const SizedBox(height: 12),\n"
    "              Text(\n"
    "                _errorMessage!,\n"
    "                style: TextStyle(\n"
    "                    color: Theme.of(context).colorScheme.error),\n"
    "              ),\n"
    "            ],\n"
    "            const SizedBox(height: 24),\n"
    "            FilledButton(\n"
    "              onPressed: _isLoading ? null : _submit,\n"
    "              child: _isLoading\n"
    "                  ? const SizedBox(\n"
    "                      height: 20,\n"
    "                      width: 20,\n"
    "                      child: CircularProgressIndicator(strokeWidth: 2),\n"
    "                    )\n"
    "                  : const Text('Enviar avaliacao'),\n"
    "            ),\n"
    "          ],\n"
    "        ),\n"
    "      ),\n"
    "    );\n"
    "  }\n"
    "}\n"
)

# ── 2. provider_detail_page.dart — _ReviewTile: trocar estrelas por nota numérica ──

replace(
    os.path.join('lib', 'features', 'provider_detail', 'provider_detail_page.dart'),
    "        Row(\n"
    "          children: [\n"
    "            Row(\n"
    "              children: List.generate(5, (i) {\n"
    "                return Icon(\n"
    "                  i < review.rating ? Icons.star : Icons.star_border,\n"
    "                  color: Colors.amber,\n"
    "                  size: 18,\n"
    "                );\n"
    "              }),\n"
    "            ),\n"
    "            const SizedBox(width: 8),\n"
    "            Text(\n"
    "              review.reviewerName,\n"
    "              style: const TextStyle(fontWeight: FontWeight.w600),\n"
    "            ),\n"
    "          ],\n"
    "        ),",
    "        Row(\n"
    "          children: [\n"
    "            Container(\n"
    "              width: 36,\n"
    "              height: 36,\n"
    "              alignment: Alignment.center,\n"
    "              decoration: BoxDecoration(\n"
    "                color: _ratingColor(review.rating),\n"
    "                shape: BoxShape.circle,\n"
    "              ),\n"
    "              child: Text(\n"
    "                '${review.rating}',\n"
    "                style: const TextStyle(\n"
    "                  color: Colors.white,\n"
    "                  fontWeight: FontWeight.bold,\n"
    "                  fontSize: 14,\n"
    "                ),\n"
    "              ),\n"
    "            ),\n"
    "            const SizedBox(width: 10),\n"
    "            Text(\n"
    "              review.reviewerName,\n"
    "              style: const TextStyle(fontWeight: FontWeight.w600),\n"
    "            ),\n"
    "          ],\n"
    "        ),"
)

# Adicionar método _ratingColor ao _ReviewTile
replace(
    os.path.join('lib', 'features', 'provider_detail', 'provider_detail_page.dart'),
    "  String _formatDate(DateTime date) {",
    "  Color _ratingColor(int rating) {\n"
    "    if (rating <= 4) return Colors.red;\n"
    "    if (rating <= 6) return Colors.orange;\n"
    "    if (rating <= 8) return Colors.amber.shade700;\n"
    "    return Colors.green;\n"
    "  }\n"
    "\n"
    "  String _formatDate(DateTime date) {"
)

# ── 3. categories_repository.dart — adicionar suggestCategory ─────────────────

replace(
    os.path.join('lib', 'data', 'repositories', 'categories_repository.dart'),
    "  /// Stream de categorias ativas ordenadas pelo campo [order].\n"
    "  Stream<List<CategoryModel>> watchActiveCategories() {",
    "  Future<void> suggestCategory({required String name, required String suggestedByUid}) async {\n"
    "    await _firestore.collection('category_suggestions').add({\n"
    "      'name': name,\n"
    "      'suggestedByUid': suggestedByUid,\n"
    "      'status': 'pending',\n"
    "      'createdAt': FieldValue.serverTimestamp(),\n"
    "    });\n"
    "  }\n"
    "\n"
    "  /// Stream de categorias ativas ordenadas pelo campo [order].\n"
    "  Stream<List<CategoryModel>> watchActiveCategories() {"
)

# ── 4. suggest_provider_page.dart ─────────────────────────────────────────────

write(
    os.path.join('lib', 'features', 'suggestions', 'suggest_provider_page.dart'),
    "import 'package:flutter/material.dart';\n"
    "import '../../data/models/category_model.dart';\n"
    "import '../../data/models/provider_model.dart';\n"
    "import '../../data/models/user_model.dart';\n"
    "import '../../data/repositories/categories_repository.dart';\n"
    "import '../../data/repositories/providers_repository.dart';\n"
    "\n"
    "class SuggestProviderPage extends StatefulWidget {\n"
    "  final UserModel currentUser;\n"
    "\n"
    "  const SuggestProviderPage({super.key, required this.currentUser});\n"
    "\n"
    "  @override\n"
    "  State<SuggestProviderPage> createState() => _SuggestProviderPageState();\n"
    "}\n"
    "\n"
    "class _SuggestProviderPageState extends State<SuggestProviderPage> {\n"
    "  // modo: true = sugerir prestador | false = sugerir categoria\n"
    "  bool _isProviderMode = true;\n"
    "\n"
    "  // prestador\n"
    "  final _nameController = TextEditingController();\n"
    "  final _phoneController = TextEditingController();\n"
    "  final _whatsappController = TextEditingController();\n"
    "  final _descriptionController = TextEditingController();\n"
    "  CategoryModel? _selectedCategory;\n"
    "  List<CategoryModel> _categories = [];\n"
    "  bool _loadingCategories = true;\n"
    "  String? _categoriesError;\n"
    "\n"
    "  // categoria\n"
    "  final _categoryNameController = TextEditingController();\n"
    "\n"
    "  final _providersRepository = ProvidersRepository();\n"
    "  final _categoriesRepository = CategoriesRepository();\n"
    "\n"
    "  bool _isLoading = false;\n"
    "  String? _errorMessage;\n"
    "\n"
    "  @override\n"
    "  void initState() {\n"
    "    super.initState();\n"
    "    _loadCategories();\n"
    "  }\n"
    "\n"
    "  @override\n"
    "  void dispose() {\n"
    "    _nameController.dispose();\n"
    "    _phoneController.dispose();\n"
    "    _whatsappController.dispose();\n"
    "    _descriptionController.dispose();\n"
    "    _categoryNameController.dispose();\n"
    "    super.dispose();\n"
    "  }\n"
    "\n"
    "  Future<void> _loadCategories() async {\n"
    "    try {\n"
    "      final cats = await _categoriesRepository.fetchActiveCategories();\n"
    "      if (mounted) {\n"
    "        setState(() {\n"
    "          _categories = cats;\n"
    "          _loadingCategories = false;\n"
    "        });\n"
    "      }\n"
    "    } catch (e) {\n"
    "      if (mounted) {\n"
    "        setState(() {\n"
    "          _categoriesError =\n"
    "              'Nao foi possivel carregar as categorias. Tente novamente.';\n"
    "          _loadingCategories = false;\n"
    "        });\n"
    "      }\n"
    "    }\n"
    "  }\n"
    "\n"
    "  Future<void> _submitProvider() async {\n"
    "    final name = _nameController.text.trim();\n"
    "    if (name.isEmpty) {\n"
    "      setState(() => _errorMessage = 'Informe o nome do prestador.');\n"
    "      return;\n"
    "    }\n"
    "    if (_selectedCategory == null) {\n"
    "      setState(() => _errorMessage = 'Selecione uma categoria.');\n"
    "      return;\n"
    "    }\n"
    "    if (_phoneController.text.trim().isEmpty &&\n"
    "        _whatsappController.text.trim().isEmpty) {\n"
    "      setState(\n"
    "        () => _errorMessage =\n"
    "            'Informe ao menos um contato (telefone ou WhatsApp).',\n"
    "      );\n"
    "      return;\n"
    "    }\n"
    "    setState(() {\n"
    "      _isLoading = true;\n"
    "      _errorMessage = null;\n"
    "    });\n"
    "    try {\n"
    "      final provider = ProviderModel(\n"
    "        id: '',\n"
    "        name: name,\n"
    "        categoryId: _selectedCategory!.id,\n"
    "        categoryName: _selectedCategory!.name,\n"
    "        phone: _phoneController.text.trim(),\n"
    "        whatsapp: _whatsappController.text.trim(),\n"
    "        description: _descriptionController.text.trim(),\n"
    "        avgRating: 0,\n"
    "        ratingCount: 0,\n"
    "        isActive: false,\n"
    "        status: 'pending',\n"
    "        suggestedBy: widget.currentUser.uid,\n"
    "      );\n"
    "      await _providersRepository.suggestProvider(provider: provider);\n"
    "      if (mounted) _showSuccessDialog('Sugestao de prestador enviada!');\n"
    "    } catch (e) {\n"
    "      if (mounted) {\n"
    "        setState(() => _errorMessage = 'Erro ao enviar. Tente novamente.');\n"
    "      }\n"
    "    } finally {\n"
    "      if (mounted) setState(() => _isLoading = false);\n"
    "    }\n"
    "  }\n"
    "\n"
    "  Future<void> _submitCategory() async {\n"
    "    final name = _categoryNameController.text.trim();\n"
    "    if (name.isEmpty) {\n"
    "      setState(() => _errorMessage = 'Informe o nome da categoria.');\n"
    "      return;\n"
    "    }\n"
    "    setState(() {\n"
    "      _isLoading = true;\n"
    "      _errorMessage = null;\n"
    "    });\n"
    "    try {\n"
    "      await _categoriesRepository.suggestCategory(\n"
    "        name: name,\n"
    "        suggestedByUid: widget.currentUser.uid,\n"
    "      );\n"
    "      if (mounted) _showSuccessDialog('Sugestao de categoria enviada!');\n"
    "    } catch (e) {\n"
    "      if (mounted) {\n"
    "        setState(() => _errorMessage = 'Erro ao enviar. Tente novamente.');\n"
    "      }\n"
    "    } finally {\n"
    "      if (mounted) setState(() => _isLoading = false);\n"
    "    }\n"
    "  }\n"
    "\n"
    "  void _showSuccessDialog(String titulo) {\n"
    "    showDialog(\n"
    "      context: context,\n"
    "      builder: (ctx) => AlertDialog(\n"
    "        title: Text(titulo),\n"
    "        content: const Text(\n"
    "          'Obrigado! Sua sugestao foi recebida e sera analisada pelo nosso time.',\n"
    "        ),\n"
    "        actions: [\n"
    "          FilledButton(\n"
    "            onPressed: () {\n"
    "              Navigator.pop(ctx);\n"
    "              Navigator.pop(context);\n"
    "            },\n"
    "            child: const Text('OK'),\n"
    "          ),\n"
    "        ],\n"
    "      ),\n"
    "    );\n"
    "  }\n"
    "\n"
    "  @override\n"
    "  Widget build(BuildContext context) {\n"
    "    return Scaffold(\n"
    "      appBar: AppBar(title: const Text('Fazer uma sugestao')),\n"
    "      body: SingleChildScrollView(\n"
    "        padding: const EdgeInsets.all(20),\n"
    "        child: Column(\n"
    "          crossAxisAlignment: CrossAxisAlignment.stretch,\n"
    "          children: [\n"
    "            SegmentedButton<bool>(\n"
    "              segments: const [\n"
    "                ButtonSegment(\n"
    "                  value: true,\n"
    "                  label: Text('Sugerir prestador'),\n"
    "                  icon: Icon(Icons.person_add_outlined),\n"
    "                ),\n"
    "                ButtonSegment(\n"
    "                  value: false,\n"
    "                  label: Text('Sugerir categoria'),\n"
    "                  icon: Icon(Icons.category_outlined),\n"
    "                ),\n"
    "              ],\n"
    "              selected: {_isProviderMode},\n"
    "              onSelectionChanged: (val) => setState(() {\n"
    "                _isProviderMode = val.first;\n"
    "                _errorMessage = null;\n"
    "              }),\n"
    "            ),\n"
    "            const SizedBox(height: 24),\n"
    "            if (_isProviderMode) ...[\n"
    "              const Text(\n"
    "                'Conhece um bom prestador de servico? Indique aqui!',\n"
    "                style: TextStyle(fontSize: 16),\n"
    "              ),\n"
    "              const Text(\n"
    "                'Sua sugestao sera revisada e, se aprovada, aparecera no app.',\n"
    "                style: TextStyle(fontSize: 14, color: Colors.grey),\n"
    "              ),\n"
    "              const SizedBox(height: 20),\n"
    "              TextField(\n"
    "                controller: _nameController,\n"
    "                decoration: const InputDecoration(\n"
    "                  labelText: 'Nome do prestador *',\n"
    "                  border: OutlineInputBorder(),\n"
    "                ),\n"
    "                textCapitalization: TextCapitalization.words,\n"
    "              ),\n"
    "              const SizedBox(height: 16),\n"
    "              if (_loadingCategories)\n"
    "                const Center(child: CircularProgressIndicator())\n"
    "              else if (_categoriesError != null)\n"
    "                Column(\n"
    "                  crossAxisAlignment: CrossAxisAlignment.stretch,\n"
    "                  children: [\n"
    "                    Text(\n"
    "                      _categoriesError!,\n"
    "                      style: TextStyle(\n"
    "                          color: Theme.of(context).colorScheme.error),\n"
    "                    ),\n"
    "                    const SizedBox(height: 8),\n"
    "                    OutlinedButton(\n"
    "                      onPressed: () {\n"
    "                        setState(() {\n"
    "                          _loadingCategories = true;\n"
    "                          _categoriesError = null;\n"
    "                        });\n"
    "                        _loadCategories();\n"
    "                      },\n"
    "                      child: const Text('Tentar novamente'),\n"
    "                    ),\n"
    "                  ],\n"
    "                )\n"
    "              else\n"
    "                InputDecorator(\n"
    "                  decoration: const InputDecoration(\n"
    "                    labelText: 'Categoria *',\n"
    "                    border: OutlineInputBorder(),\n"
    "                  ),\n"
    "                  child: DropdownButton<CategoryModel>(\n"
    "                    value: _selectedCategory,\n"
    "                    isExpanded: true,\n"
    "                    underline: const SizedBox.shrink(),\n"
    "                    hint: const Text('Selecione'),\n"
    "                    items: _categories\n"
    "                        .map((cat) => DropdownMenuItem(\n"
    "                              value: cat,\n"
    "                              child: Text(cat.name),\n"
    "                            ))\n"
    "                        .toList(),\n"
    "                    onChanged: (cat) =>\n"
    "                        setState(() => _selectedCategory = cat),\n"
    "                  ),\n"
    "                ),\n"
    "              const SizedBox(height: 16),\n"
    "              TextField(\n"
    "                controller: _phoneController,\n"
    "                decoration: const InputDecoration(\n"
    "                  labelText: 'Telefone',\n"
    "                  border: OutlineInputBorder(),\n"
    "                ),\n"
    "                keyboardType: TextInputType.phone,\n"
    "              ),\n"
    "              const SizedBox(height: 16),\n"
    "              TextField(\n"
    "                controller: _whatsappController,\n"
    "                decoration: const InputDecoration(\n"
    "                  labelText: 'WhatsApp (somente numeros com DDD)',\n"
    "                  border: OutlineInputBorder(),\n"
    "                ),\n"
    "                keyboardType: TextInputType.phone,\n"
    "              ),\n"
    "              const SizedBox(height: 16),\n"
    "              TextField(\n"
    "                controller: _descriptionController,\n"
    "                decoration: const InputDecoration(\n"
    "                  labelText: 'O que esse prestador faz?',\n"
    "                  border: OutlineInputBorder(),\n"
    "                  alignLabelWithHint: true,\n"
    "                ),\n"
    "                maxLines: 4,\n"
    "                textCapitalization: TextCapitalization.sentences,\n"
    "              ),\n"
    "            ] else ...[\n"
    "              const Text(\n"
    "                'Nao encontrou a categoria que procura?',\n"
    "                style: TextStyle(fontSize: 16),\n"
    "              ),\n"
    "              const Text(\n"
    "                'Sugira uma nova categoria para ser avaliada pelo nosso time.',\n"
    "                style: TextStyle(fontSize: 14, color: Colors.grey),\n"
    "              ),\n"
    "              const SizedBox(height: 20),\n"
    "              TextField(\n"
    "                controller: _categoryNameController,\n"
    "                decoration: const InputDecoration(\n"
    "                  labelText: 'Nome da categoria *',\n"
    "                  border: OutlineInputBorder(),\n"
    "                ),\n"
    "                textCapitalization: TextCapitalization.words,\n"
    "              ),\n"
    "            ],\n"
    "            if (_errorMessage != null) ...[\n"
    "              const SizedBox(height: 12),\n"
    "              Text(\n"
    "                _errorMessage!,\n"
    "                style:\n"
    "                    TextStyle(color: Theme.of(context).colorScheme.error),\n"
    "              ),\n"
    "            ],\n"
    "            const SizedBox(height: 24),\n"
    "            FilledButton(\n"
    "              onPressed: _isLoading\n"
    "                  ? null\n"
    "                  : (_isProviderMode ? _submitProvider : _submitCategory),\n"
    "              child: _isLoading\n"
    "                  ? const SizedBox(\n"
    "                      height: 20,\n"
    "                      width: 20,\n"
    "                      child: CircularProgressIndicator(strokeWidth: 2),\n"
    "                    )\n"
    "                  : const Text('Enviar sugestao'),\n"
    "            ),\n"
    "          ],\n"
    "        ),\n"
    "      ),\n"
    "    );\n"
    "  }\n"
    "}\n"
)

# ── 5. home_page.dart — renomear botão ────────────────────────────────────────

replace(
    os.path.join('lib', 'features', 'home', 'home_page.dart'),
    "                  icon: const Icon(Icons.add_business),\n"
    "                  label: const Text('Sugerir prestador'),",
    "                  icon: const Icon(Icons.add_business),\n"
    "                  label: const Text('Fazer uma sugestao'),"
)
