// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0WYLBvpKFK8WJ2Rt4lhHiT_mErMTRj0c',
    appId: '1:980349637154:android:41e1633447edeeee04307b',
    messagingSenderId: '980349637154',
    projectId: 'prestservbuscavida',
    storageBucket: 'prestservbuscavida.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTkLQ-1eo0OhaWOUV5jxpe0lbGHPd2aEQ',
    appId: '1:980349637154:ios:256dcb800e44da4b04307b',
    messagingSenderId: '980349637154',
    projectId: 'prestservbuscavida',
    storageBucket: 'prestservbuscavida.firebasestorage.app',
    iosClientId: '980349637154-pmo2tob50gvo5msaa4m5qj3q63jghsfc.apps.googleusercontent.com',
    iosBundleId: 'com.buscavida.prestservbuscavida',
  );
}
