// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0WYLBvpKFK8WJ2Rt4lhHiT_mErMTRj0c',
    appId: '1:980349637154:android:41e1633447edeeee04307b',
    messagingSenderId: '980349637154',
    projectId: 'prestservbuscavida',
    storageBucket: 'prestservbuscavida.firebasestorage.app',
  );

  }

  );
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWRduhBuvJD0qjUCdd1w57ec8PSjC13gE',
    appId: '1:980349637154:web:0e759d1f24afac9804307b',
    messagingSenderId: '980349637154',
    projectId: 'prestservbuscavida',
    authDomain: 'prestservbuscavida.firebaseapp.com',
    storageBucket: 'prestservbuscavida.firebasestorage.app',
    measurementId: 'G-VQN36MNQ9T',
  );
}